"""Add active field to principles

Revision ID: 403da7be3d7b
Revises: 81fc213c1bb4
Create Date: 2018-07-06 08:02:17.218615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403da7be3d7b'
down_revision = '81fc213c1bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('principles', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('principles', 'active')
    # ### end Alembic commands ###
