"""Initial commit

Revision ID: 4162eecef2d0
Revises: 
Create Date: 2018-06-15 09:34:37.102373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4162eecef2d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principle', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principle')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_fqdn', sa.String(length=300), nullable=True),
    sa.Column('principle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    op.drop_table('principles')
    # ### end Alembic commands ###
